/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-06 at 11:05:16 UTC 
 * Modify at your own risk.
 */

package com.appspot.maulikabd.mresultreport;

/**
 * Service definition for Mresultreport (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link MresultreportRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Mresultreport extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.19.0 of the mresultreport library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://maulikabd.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "mresultreport/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Mresultreport(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Mresultreport(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the MresultreportOperations collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Mresultreport mresultreport = new Mresultreport(...);}
   *   {@code Mresultreport.MresultreportOperations.List request = mresultreport.mresultreport().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public MresultreportOperations mresultreport() {
    return new MresultreportOperations();
  }

  /**
   * The "mresultreport" collection of methods.
   */
  public class MresultreportOperations {

    /**
     * Create a request for the method "mresultreport.addResultFileName".
     *
     * This request holds the parameters needed by the mresultreport server.  After setting any optional
     * parameters, call the {@link AddResultFileName#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage}
     * @return the request
     */
    public AddResultFileName addResultFileName(com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage content) throws java.io.IOException {
      AddResultFileName result = new AddResultFileName(content);
      initialize(result);
      return result;
    }

    public class AddResultFileName extends MresultreportRequest<Void> {

      private static final String REST_PATH = "addresultfilename";

      /**
       * Create a request for the method "mresultreport.addResultFileName".
       *
       * This request holds the parameters needed by the the mresultreport server.  After setting any
       * optional parameters, call the {@link AddResultFileName#execute()} method to invoke the remote
       * operation. <p> {@link AddResultFileName#initialize(com.google.api.client.googleapis.services.Ab
       * stractGoogleClientRequest)} must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage}
       * @since 1.13
       */
      protected AddResultFileName(com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage content) {
        super(Mresultreport.this, "POST", REST_PATH, content, Void.class);
      }

      @Override
      public AddResultFileName setAlt(java.lang.String alt) {
        return (AddResultFileName) super.setAlt(alt);
      }

      @Override
      public AddResultFileName setFields(java.lang.String fields) {
        return (AddResultFileName) super.setFields(fields);
      }

      @Override
      public AddResultFileName setKey(java.lang.String key) {
        return (AddResultFileName) super.setKey(key);
      }

      @Override
      public AddResultFileName setOauthToken(java.lang.String oauthToken) {
        return (AddResultFileName) super.setOauthToken(oauthToken);
      }

      @Override
      public AddResultFileName setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (AddResultFileName) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public AddResultFileName setQuotaUser(java.lang.String quotaUser) {
        return (AddResultFileName) super.setQuotaUser(quotaUser);
      }

      @Override
      public AddResultFileName setUserIp(java.lang.String userIp) {
        return (AddResultFileName) super.setUserIp(userIp);
      }

      @Override
      public AddResultFileName set(String parameterName, Object value) {
        return (AddResultFileName) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "mresultreport.addResultRow".
     *
     * This request holds the parameters needed by the mresultreport server.  After setting any optional
     * parameters, call the {@link AddResultRow#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultRowMessage}
     * @return the request
     */
    public AddResultRow addResultRow(com.appspot.maulikabd.mresultreport.model.ResultResultRowMessage content) throws java.io.IOException {
      AddResultRow result = new AddResultRow(content);
      initialize(result);
      return result;
    }

    public class AddResultRow extends MresultreportRequest<Void> {

      private static final String REST_PATH = "addresultrow";

      /**
       * Create a request for the method "mresultreport.addResultRow".
       *
       * This request holds the parameters needed by the the mresultreport server.  After setting any
       * optional parameters, call the {@link AddResultRow#execute()} method to invoke the remote
       * operation. <p> {@link
       * AddResultRow#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultRowMessage}
       * @since 1.13
       */
      protected AddResultRow(com.appspot.maulikabd.mresultreport.model.ResultResultRowMessage content) {
        super(Mresultreport.this, "POST", REST_PATH, content, Void.class);
      }

      @Override
      public AddResultRow setAlt(java.lang.String alt) {
        return (AddResultRow) super.setAlt(alt);
      }

      @Override
      public AddResultRow setFields(java.lang.String fields) {
        return (AddResultRow) super.setFields(fields);
      }

      @Override
      public AddResultRow setKey(java.lang.String key) {
        return (AddResultRow) super.setKey(key);
      }

      @Override
      public AddResultRow setOauthToken(java.lang.String oauthToken) {
        return (AddResultRow) super.setOauthToken(oauthToken);
      }

      @Override
      public AddResultRow setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (AddResultRow) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public AddResultRow setQuotaUser(java.lang.String quotaUser) {
        return (AddResultRow) super.setQuotaUser(quotaUser);
      }

      @Override
      public AddResultRow setUserIp(java.lang.String userIp) {
        return (AddResultRow) super.setUserIp(userIp);
      }

      @Override
      public AddResultRow set(String parameterName, Object value) {
        return (AddResultRow) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "mresultreport.getFiles".
     *
     * This request holds the parameters needed by the mresultreport server.  After setting any optional
     * parameters, call the {@link GetFiles#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public GetFiles getFiles() throws java.io.IOException {
      GetFiles result = new GetFiles();
      initialize(result);
      return result;
    }

    public class GetFiles extends MresultreportRequest<com.appspot.maulikabd.mresultreport.model.ResultFileCollectionMessage> {

      private static final String REST_PATH = "getfiles";

      /**
       * Create a request for the method "mresultreport.getFiles".
       *
       * This request holds the parameters needed by the the mresultreport server.  After setting any
       * optional parameters, call the {@link GetFiles#execute()} method to invoke the remote operation.
       * <p> {@link
       * GetFiles#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected GetFiles() {
        super(Mresultreport.this, "POST", REST_PATH, null, com.appspot.maulikabd.mresultreport.model.ResultFileCollectionMessage.class);
      }

      @Override
      public GetFiles setAlt(java.lang.String alt) {
        return (GetFiles) super.setAlt(alt);
      }

      @Override
      public GetFiles setFields(java.lang.String fields) {
        return (GetFiles) super.setFields(fields);
      }

      @Override
      public GetFiles setKey(java.lang.String key) {
        return (GetFiles) super.setKey(key);
      }

      @Override
      public GetFiles setOauthToken(java.lang.String oauthToken) {
        return (GetFiles) super.setOauthToken(oauthToken);
      }

      @Override
      public GetFiles setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetFiles) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetFiles setQuotaUser(java.lang.String quotaUser) {
        return (GetFiles) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetFiles setUserIp(java.lang.String userIp) {
        return (GetFiles) super.setUserIp(userIp);
      }

      @Override
      public GetFiles set(String parameterName, Object value) {
        return (GetFiles) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "mresultreport.getGraph".
     *
     * This request holds the parameters needed by the mresultreport server.  After setting any optional
     * parameters, call the {@link GetGraph#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultStudentId}
     * @return the request
     */
    public GetGraph getGraph(com.appspot.maulikabd.mresultreport.model.ResultResultStudentId content) throws java.io.IOException {
      GetGraph result = new GetGraph(content);
      initialize(result);
      return result;
    }

    public class GetGraph extends MresultreportRequest<com.appspot.maulikabd.mresultreport.model.ResultGraphMessage> {

      private static final String REST_PATH = "getgraph";

      /**
       * Create a request for the method "mresultreport.getGraph".
       *
       * This request holds the parameters needed by the the mresultreport server.  After setting any
       * optional parameters, call the {@link GetGraph#execute()} method to invoke the remote operation.
       * <p> {@link
       * GetGraph#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultStudentId}
       * @since 1.13
       */
      protected GetGraph(com.appspot.maulikabd.mresultreport.model.ResultResultStudentId content) {
        super(Mresultreport.this, "POST", REST_PATH, content, com.appspot.maulikabd.mresultreport.model.ResultGraphMessage.class);
      }

      @Override
      public GetGraph setAlt(java.lang.String alt) {
        return (GetGraph) super.setAlt(alt);
      }

      @Override
      public GetGraph setFields(java.lang.String fields) {
        return (GetGraph) super.setFields(fields);
      }

      @Override
      public GetGraph setKey(java.lang.String key) {
        return (GetGraph) super.setKey(key);
      }

      @Override
      public GetGraph setOauthToken(java.lang.String oauthToken) {
        return (GetGraph) super.setOauthToken(oauthToken);
      }

      @Override
      public GetGraph setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetGraph) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetGraph setQuotaUser(java.lang.String quotaUser) {
        return (GetGraph) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetGraph setUserIp(java.lang.String userIp) {
        return (GetGraph) super.setUserIp(userIp);
      }

      @Override
      public GetGraph set(String parameterName, Object value) {
        return (GetGraph) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "mresultreport.getStudent".
     *
     * This request holds the parameters needed by the mresultreport server.  After setting any optional
     * parameters, call the {@link GetStudent#execute()} method to invoke the remote operation.
     *
     * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage}
     * @return the request
     */
    public GetStudent getStudent(com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage content) throws java.io.IOException {
      GetStudent result = new GetStudent(content);
      initialize(result);
      return result;
    }

    public class GetStudent extends MresultreportRequest<com.appspot.maulikabd.mresultreport.model.ResultResultStudentIdCollection> {

      private static final String REST_PATH = "getstudent";

      /**
       * Create a request for the method "mresultreport.getStudent".
       *
       * This request holds the parameters needed by the the mresultreport server.  After setting any
       * optional parameters, call the {@link GetStudent#execute()} method to invoke the remote
       * operation. <p> {@link
       * GetStudent#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param content the {@link com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage}
       * @since 1.13
       */
      protected GetStudent(com.appspot.maulikabd.mresultreport.model.ResultResultFileMessage content) {
        super(Mresultreport.this, "POST", REST_PATH, content, com.appspot.maulikabd.mresultreport.model.ResultResultStudentIdCollection.class);
      }

      @Override
      public GetStudent setAlt(java.lang.String alt) {
        return (GetStudent) super.setAlt(alt);
      }

      @Override
      public GetStudent setFields(java.lang.String fields) {
        return (GetStudent) super.setFields(fields);
      }

      @Override
      public GetStudent setKey(java.lang.String key) {
        return (GetStudent) super.setKey(key);
      }

      @Override
      public GetStudent setOauthToken(java.lang.String oauthToken) {
        return (GetStudent) super.setOauthToken(oauthToken);
      }

      @Override
      public GetStudent setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetStudent) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetStudent setQuotaUser(java.lang.String quotaUser) {
        return (GetStudent) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetStudent setUserIp(java.lang.String userIp) {
        return (GetStudent) super.setUserIp(userIp);
      }

      @Override
      public GetStudent set(String parameterName, Object value) {
        return (GetStudent) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Mresultreport}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Mresultreport}. */
    @Override
    public Mresultreport build() {
      return new Mresultreport(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link MresultreportRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMresultreportRequestInitializer(
        MresultreportRequestInitializer mresultreportRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(mresultreportRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
