/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-06 at 11:05:16 UTC 
 * Modify at your own risk.
 */

package com.appspot.maulikabd.mresultreport.model;

/**
 * Model definition for ResultSubMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the mresultreport. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ResultSubMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("sub_name")
  private java.lang.String subName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSubName() {
    return subName;
  }

  /**
   * @param subName subName or {@code null} for none
   */
  public ResultSubMessage setSubName(java.lang.String subName) {
    this.subName = subName;
    return this;
  }

  @Override
  public ResultSubMessage set(String fieldName, Object value) {
    return (ResultSubMessage) super.set(fieldName, value);
  }

  @Override
  public ResultSubMessage clone() {
    return (ResultSubMessage) super.clone();
  }

}
