/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-06 at 11:05:16 UTC 
 * Modify at your own risk.
 */

package com.appspot.maulikabd.mresultreport.model;

/**
 * Model definition for ResultResultRowMessage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the mresultreport. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ResultResultRowMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String file;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("student_class")
  private java.lang.String studentClass;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("student_div")
  private java.lang.String studentDiv;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("student_id")
  private java.lang.String studentId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("student_marks")
  private java.lang.String studentMarks;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("student_name")
  private java.lang.String studentName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("student_sub")
  private java.lang.String studentSub;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFile() {
    return file;
  }

  /**
   * @param file file or {@code null} for none
   */
  public ResultResultRowMessage setFile(java.lang.String file) {
    this.file = file;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStudentClass() {
    return studentClass;
  }

  /**
   * @param studentClass studentClass or {@code null} for none
   */
  public ResultResultRowMessage setStudentClass(java.lang.String studentClass) {
    this.studentClass = studentClass;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStudentDiv() {
    return studentDiv;
  }

  /**
   * @param studentDiv studentDiv or {@code null} for none
   */
  public ResultResultRowMessage setStudentDiv(java.lang.String studentDiv) {
    this.studentDiv = studentDiv;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStudentId() {
    return studentId;
  }

  /**
   * @param studentId studentId or {@code null} for none
   */
  public ResultResultRowMessage setStudentId(java.lang.String studentId) {
    this.studentId = studentId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStudentMarks() {
    return studentMarks;
  }

  /**
   * @param studentMarks studentMarks or {@code null} for none
   */
  public ResultResultRowMessage setStudentMarks(java.lang.String studentMarks) {
    this.studentMarks = studentMarks;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStudentName() {
    return studentName;
  }

  /**
   * @param studentName studentName or {@code null} for none
   */
  public ResultResultRowMessage setStudentName(java.lang.String studentName) {
    this.studentName = studentName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStudentSub() {
    return studentSub;
  }

  /**
   * @param studentSub studentSub or {@code null} for none
   */
  public ResultResultRowMessage setStudentSub(java.lang.String studentSub) {
    this.studentSub = studentSub;
    return this;
  }

  @Override
  public ResultResultRowMessage set(String fieldName, Object value) {
    return (ResultResultRowMessage) super.set(fieldName, value);
  }

  @Override
  public ResultResultRowMessage clone() {
    return (ResultResultRowMessage) super.clone();
  }

}
